# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog


job:
  chdir: False
# output directory, generated dynamically on each run
run:
  dir: ${paths.out_data_dir}/${tests.scene_file}_${tests.tag}

sweep:
  dir: ${paths.out_data_dir}
  subdir: ${tests.scene_file}_${tests.tag}
